// Auto-generated by: supabase gen types typescript --project-id <id> > src/types/database.ts
// Re-run after each migration to keep types in sync with the database schema.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string | null
          name: string | null
          created_at: string
        }
        Insert: {
          id?: string
          email?: string | null
          name?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          email?: string | null
          name?: string | null
          created_at?: string
        }
        Relationships: []
      }
      habits: {
        Row: {
          id: string
          user_id: string
          name: string
          emoji: string
          frequency: number[]
          sort_order: number
          archived_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          emoji: string
          frequency: number[]
          sort_order?: number
          archived_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          emoji?: string
          frequency?: number[]
          sort_order?: number
          archived_at?: string | null
          created_at?: string
        }
        Relationships: []
      }
      habit_logs: {
        Row: {
          id: string
          user_id: string
          habit_id: string
          logged_date: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          habit_id: string
          logged_date: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          habit_id?: string
          logged_date?: string
          created_at?: string
        }
        Relationships: []
      }
      challenges: {
        Row: {
          id: string
          user_id: string
          habit_id: string
          name: string
          tier: string
          goal_days: number
          start_date: string
          end_date: string
          reason: string | null
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          habit_id: string
          name: string
          tier: string
          goal_days: number
          start_date: string
          end_date: string
          reason?: string | null
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          habit_id?: string
          name?: string
          tier?: string
          goal_days?: number
          start_date?: string
          end_date?: string
          reason?: string | null
          status?: string
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
